version: '3'
services:
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: revenue
      POSTGRES_DB: revenue
      POSTGRES_USER: revenue
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      - app-tier
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
  
  api1:
    build:
      context: .
      dockerfile: Dockerfile.api1
    container_name: api1
    depends_on:
      - postgres_db
    restart: "on-failure:3"
    networks:
      - app-tier
    ports: 
      - 5000:5000
    volumes:
      - .:/app

  api2:
    build:
      context: .
      dockerfile: Dockerfile.api2
    container_name: api2
    depends_on:
      - postgres_db
      - api1
    networks:
      - app-tier
    ports: 
      - 5001:5001
    volumes:
      - .:/app
  
  gui:
    build:
      context: .
      dockerfile: Dockerfile.gui
    container_name: gui
    depends_on:
      - postgres_db
      - api1
      - api2
    networks:
      - app-tier
    ports: 
      - 5002:5002
    volumes:
      - .:/app

networks:
  app-tier:
    driver: bridge
